### ISSUE TITLE
No API key verify

### ISSUE THREAD

**Issue by burdukow** [MrSedan/GifClip-Linux#3]
## What I did:
1. git clone
2. install requirements
3. launch .py file

## What I got:
without .env file it returns an exception:
```sh
Traceback (most recent call last):
  File "/home/burdukov/GifClip-Linux/main.py", line 53, in on_button_clicked
    for i, img in enumerate(response['results']):
KeyError: 'results'
```

## What need 2do:
add validation check for dotenv file 'n' check token for availability

**Comment by MrSedan** [comment]
Check [requirements section](https://github.com/MrSedan/GifClip-Linux#requirements) in [README.md](https://github.com/MrSedan/GifClip-Linux/blob/master/README.md) and the problem will gone!

**Comment by burdukow** [comment]
Also, the file can be "magicaly" deleted and the exception will not tell the reason.
